# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicCareer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MusicCareerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MusicCareer')),
            ],
        ),
        migrations.CreateModel(
            name='MusicInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('musicCareerList', models.ManyToManyField(to='accounts.MusicCareerList')),
            ],
        ),
        migrations.AddField(
            model_name='musiccareer',
            name='musicInstrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MusicInstrument'),
        ),
    ]
