# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
